# Generated by Django 3.1.5 on 2021-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('reg_no', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=3)),
                ('session', models.CharField(max_length=5)),
                ('role_id', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
