# Generated by Django 3.1.5 on 2021-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210223_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
