# Generated by Django 3.1.5 on 2021-06-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210224_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
