# Generated by Django 3.1.5 on 2021-06-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='c_score',
            field=models.IntegerField(null=True),
        ),
    ]
