# Generated by Django 3.1.5 on 2021-06-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210624_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
