# Generated by Django 3.1.5 on 2021-06-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210625_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='code',
        ),
    ]
