# Generated by Django 3.1.5 on 2021-06-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_teacherinfo_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherInfo',
        ),
        migrations.AlterField(
            model_name='departmentalhead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentinfo'),
        ),
    ]
