# Generated by Django 3.1.5 on 2021-06-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_teacherinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='u_name',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
