# Generated by Django 3.1.5 on 2021-06-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_teacherinfo_u_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='u_name',
        ),
    ]
