# Generated by Django 3.1.5 on 2021-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_teacherinfo_u_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='role_id',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
