# Generated by Django 3.1.5 on 2021-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_studentinfo_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='uploaded_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
