# Generated by Django 3.1.5 on 2021-06-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_description',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
