# Generated by Django 3.1.5 on 2021-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='code',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
