# Generated by Django 3.1.5 on 2021-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210623_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
