# Generated by Django 3.1.5 on 2021-06-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_comments_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='code',
        ),
    ]
