# Generated by Django 3.1.5 on 2021-07-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courses_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.CharField(max_length=500),
        ),
    ]
